# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 05:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField()),
                ('schedule', models.CharField(max_length=100, verbose_name='title')),
                ('video', models.FileField(max_length=200, upload_to='video/')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=100, verbose_name='title')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='exercises',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.Program'),
        ),
    ]
