# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='schedule',
            field=models.CharField(max_length=100, verbose_name='schedule'),
        ),
        migrations.AlterField(
            model_name='program',
            name='duration',
            field=models.CharField(max_length=100, verbose_name='duration'),
        ),
    ]
