# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_auto_20161128_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.Program')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='dosage',
            field=models.CharField(default='5 Reps', max_length=100, verbose_name='dosage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='exerciseentry',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.Exercise'),
        ),
        migrations.AddField(
            model_name='exerciseentry',
            name='program_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.ProgramEntry'),
        ),
    ]
